version: '3.3'

services:
  cs_be:
    build: .
    container_name: backendcompose1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8085:8080'
    restart: always

  cs_fe:
    build: .
    container_name: frontendcompose1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '4225:4200'
    restart: always

