version: '3.3'

services:
  cs_be:
    build: .
    container_name: backendcompose
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8084:8080'
    restart: always

  cs_fe:
    build: .
    container_name: frontendcompose
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '4224:4200'
    restart: always

